-- MySQL Script generated by MySQL Workbench
-- Tue 04 Apr 2023 05:32:53 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elearning` DEFAULT CHARACTER SET utf8 ;
USE `elearning` ;

-- -----------------------------------------------------
-- Table `elearning`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elearning`.`users` ;

CREATE TABLE IF NOT EXISTS `elearning`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `neptun` CHAR(6) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `neptun_UNIQUE` (`neptun` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elearning`.`courses` ;

CREATE TABLE IF NOT EXISTS `elearning`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_courses_owner_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_courses_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `elearning`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`users_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elearning`.`users_courses` ;

CREATE TABLE IF NOT EXISTS `elearning`.`users_courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `course` INT NOT NULL,
  `is_pending` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_users_courses_user_idx` (`user` ASC) VISIBLE,
  INDEX `fk_users_courses_course_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_users_courses_user`
    FOREIGN KEY (`user`)
    REFERENCES `elearning`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_courses_course`
    FOREIGN KEY (`course`)
    REFERENCES `elearning`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elearning`.`lessons` ;

CREATE TABLE IF NOT EXISTS `elearning`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `nth` INT NOT NULL,
  `body` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lessons_course_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_course`
    FOREIGN KEY (`course`)
    REFERENCES `elearning`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elearning`.`media` ;

CREATE TABLE IF NOT EXISTS `elearning`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_media_owner_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_media_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `elearning`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
