# Generated by Django 4.2 on 2023-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0002_alter_lessons_id_alter_media_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='data',
            field=models.BinaryField(),
        ),
    ]
