# Generated by Django 4.2 on 2023-04-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0003_alter_media_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='elearning_app.users'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='elearning_app.courses'),
        ),
        migrations.AlterField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='elearning_app.users'),
        ),
        migrations.AlterField(
            model_name='userscourses',
            name='course',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='elearning_app.courses'),
        ),
        migrations.AlterField(
            model_name='userscourses',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='elearning_app.users'),
        ),
    ]
